version: '3.9'

services:
  nginx:
    build: 
      context: .
      dockerfile: nginx.dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./wordpress:/var/www/html:delegated
    restart: always
    depends_on:
      - mysql
      - php
    # networks:
    #   -  web
    container_name: site_nginx
  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: wp
      MYSQL_USER: wp
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - ./mysql:/var/lib/mysql
    restart: always
    # networks:
    # -  database
    container_name: site_mysql
  php:
    build:
      context: .
      dockerfile: php.dockerfile
    volumes:
      - ./wordpress:/var/www/html:delegated
    restart: always
    container_name: site_php

  wp:
    build: 
      context: .
      dockerfile: php.dockerfile
    volumes:
      - ./wordpress:/var/www/html:delegated
    restart: always
    entrypoint: ['wp', '--allow-root']
    networks:
      - web
      - database
    container_name: site_wp
networks:
  database:
    name: database
    driver: bridge
  web:
    name: web
    driver: bridge